### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by fewensa**
1. https://github.com/arthurkhlghatyan/gql-client-rs/pull/13
2. https://github.com/fewensa/gql-client-rs/pull/2
3. https://github.com/fewensa/gql-client-rs/pull/3
4. https://github.com/fewensa/gql-client-rs/pull/4
5. https://github.com/fewensa/gql-client-rs/pull/5
6. https://github.com/fewensa/gql-client-rs/pull/6

### CODE REVIEW

**Review by arthurkhlghatyan — APPROVED** [review]

**Comment by arthurkhlghatyan** [comment]
Hey, thanks for PR @fewensa seems wasm-support is [failing](https://app.travis-ci.com/github/arthurkhlghatyan/gql-client-rs/jobs/562054659), do you think we could figure something out for this?

**Comment by fewensa** [comment]
Let's me check it late

**Comment by fewensa** [comment]
It's fixed. but now the request can not support set timeout in wasm mode. https://github.com/seanmonstar/reqwest/issues/288 https://github.com/seanmonstar/reqwest/issues/1135

**Comment by arthurkhlghatyan** [comment]
Yeah, thanks man, approved will deploy a new version in a moment

**Comment by fewensa** [comment]
Hi, You published in crate.io (1.0.3) it seems not from master branch?
https://docs.rs/crate/gql_client/1.0.3/source/src/client.rs

**Comment by arthurkhlghatyan** [comment]
Hey just published 1.0.4 from master https://crates.io/crates/gql_client/1.0.4

**Pull request merged**
