### PR TITLE
Check response code and fix ci

### PR DESCRIPTION
**Pull request by fewensa**
- Check response status and add log output for unwrap function.
- Fix CI

Related #8 

Hi @arthurkhlghatyan , I fix CI and make some changes to show log to help debug. and bump versions o 1.0.6

### CODE REVIEW

**Review by arthurkhlghatyan — APPROVED** [review]

**Comment by arthurkhlghatyan** [comment]
Hey @fewensa thanks for PR it's merged. Let's see how the workflow goes. I'm also removing development branch because it's not maintained as you requested.

Thanks.

Arthur.

**Comment by arthurkhlghatyan** [comment]
Oops. dev branch is already removed. thank you hahaha.

**Comment by fewensa** [comment]
Yes, I removed it, and I published a new https://github.com/arthurkhlghatyan/gql-client-rs/releases/tag/v1.0.6

**Comment by fewensa** [comment]
This will be publish new version to crates.io

**Comment by fewensa** [comment]
https://github.com/arthurkhlghatyan/gql-client-rs/actions/runs/2563710381


https://crates.io/crates/gql_client

**Comment by arthurkhlghatyan** [comment]
Yeah it works fine man! Very excited we finally fixed the CI hahaha. thank you

**Pull request merged**
